### PR TITLE
Feature/base predicates

### PR DESCRIPTION
**Pull request by fractaledmind**
@riyengar8 Here is my initial implementation of filtering predicates that work across both ActiveRecord and Enumerable sets. I have confined this PR to the base predicates for now to hopefully make the review more streamlined.

Also, this work builds on some smaller changes I've made in a couple recent PRs, most notably, creating a hierarchical structure for SetInstruction classes (so there are now in `master` SetInstruction classes specifically for Enumerable filtering and ActiveRecord filtering). Also, I expanded the filtering specs (and fixed one issue) so the tests are the most robust they have ever been. So, if you would want to experiment with this branch and any changes you'd want to make, if you can get the test suite to pass, you can be confident everything works.

Let me know what you think.

### CODE REVIEW

**Comment by fractaledmind** [comment]
@riyengar8: This is a gentle reminder of the existence of these PRs. Before merging any of them and cutting a new release of the gem, I would love to get your thoughts and feedback on this implementation. I've spent so much time thinking about how to implement this feature that I fear I may be a tad blind in areas, so I particularly want a second pair of eyes here

**Comment by riyengar8** [comment]
Can you talk a little bit about the result and attribute transformers that can be passed to the Enumerable filterer? Maybe give an example of how one would take advantage of those?

**Comment by riyengar8** [comment]
I don't think I have any other comments for now. Just the two bits above that I am curious about.

**Comment by fractaledmind** [comment]
> Thanks for the reminder. For some reason, every time I try to comment inline, Github tells me I cannot because the diff is outdated, no matter how often I refresh, so I'll try putting my comment out here.

Bizarre. No idea what is up there. 🤷‍♂

>I'm pretty interested in the metadata you are keeping here about the various operator types in `lib/active_set/filtering/constants.rb`. I have questions on two fronts. First, I want to try to understand the attributes themselves:
>  - I am fairly certain you are using "type" here in the computer science-y operation sense that I am used to: unary, binary, conditional or ternary, assignment. I note we only have binary operators represented here, and I am struggling to think of plausible filtering examples using an operator from one of the other types that couldn't also be represented as a binary operation, but I think I understand what this tracks.

You have this understanding basically correct. You can look at PR #48 for an example of `unary` type operations (like `is_present` or `is_false`).

>  - I don't think I'm familiar with "compound" as you are using it here. Roughly, I can see that it tracks to the number of discrete comparisons required to complete the operation; a "compound" operator actually requires multiple comparisons to resolve. Is that on the right track?

You are again on the right track here. This is to track whether the predicate of the operation is a simple object or a compound object. Consider the difference between the `eq` and `eq_any` operations.

> - I'm not quite following inclusive vs exclusive vs inconclusive. I think I could derive the pattern if it were just inclusive and exclusive, but the fact that "between" is not inclusive and "not between" is not exclusive breaks it for me so I think I need help here.

This is metadata used (and intended) exclusively for tests. The idea is, how will "identity" filtering behave? If I did `[object].filter('itself(operator)': object)`, would the `object` be returned? "inclusive" operators keep the objects, "exclusive" operators remove them, and "inconclusive" operators are precisely that. `eq` is the paradigmatic "inclusive" operator; `not_eq` is the paradigmatic "exclusive" operator; and, `lt_any` is a great "inconclusive" operator (because it would depend on the other elements in the array).

> Second, I'm wondering if you can summarize what the gem is doing with this metadata? I assume we track these bits because it changes how we handle these operations somewhere downstream? Is it only in the specs where this information is used?

The most important use is in the programmatic tests. However, I also wanted to start mapping out the problem space of filtering operations. I don't use most of them in the gem itself, but they were necessary to write programmatic tests, and I felt that attempting to find the "joints" in this problem-space would prove beneficial in the future in some way.

> Can you talk a little bit about the result and attribute transformers that can be passed to the Enumerable filterer? Maybe give an example of how one would take advantage of those?

So these are used to help me achieve logical consistency in places where Ruby doesn't help. For example, the `eq` and `not_eq` operations can be directly mapped to Ruby methods (`==` and `!=`), and these methods will behave in precisely the same way as the SQL queries across all of the data-types. Sometimes, however, Ruby has a method but not its logical inverse (like `presence_in`), so I need to flip the result Boolean to get my desired result (thus the `not_in` operation has to apply a `result_transformer`). I currently don't use the `result_transformer` for any other purpose than flipping the Boolean, and I do not imagine using it for anything else.

The `object_attribute_transformer` and `query_attribute_transformer` hooks are to help with data-preparation. I wanted to keep the `Strategy` logic as clean and generic as possible, but some operations require specific data types for the left-hand and right-hand operands. The `matches` operation is a good example; we delegate to the `=~` Ruby method, but this method requires that the left-hand side (the "object attribute") be a string and the right-hand side (the "query attribute") by a regular expression. Instead of having `if` blocks in the `Strategy`, I thought it would be cleaner to allow operations to insert themselves with hooks to prepare data as needed for the Ruby methods they are delegating to.

- - -

As a final note, I think it would help you to walk thru each of the PRs here, as I tried to systematically layer on complexity. So the final PR includes all of the operations I initially wanted to support, implemented for both strategies.

**Pull request merged**
